### ISSUE TITLE
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread

### ISSUE THREAD

**Issue by bpennypacker** [bpennypacker/WeatherFlow-Indigo-Plugin#16]
station ID: 15733

Traceback (most recent call last):
  File "plugin.py", line 681, in runConcurrentThread
  File "plugin.py", line 590, in _process_message
  File "plugin.py", line 741, in process_obs_sky
TypeError: float() argument must be a string or a number

new Sky device - set display to 'precipitation accumulated'

**Comment by bpennypacker** [comment]
Fixed in #22 (v0.2.2)
