### ISSUE TITLE
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

### ISSUE THREAD

**Issue by PSSOMgdelb6** [bpennypacker/WeatherFlow-Indigo-Plugin#18]
`WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 681, in runConcurrentThread
  File "plugin.py", line 622, in _process_message
  File "plugin.py", line 816, in process_obs_tempest
TypeError: float() argument must be a string or a number

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
`

Indigo 7.4
WF 0.2.1
Tempest

**Comment by PSSOMgdelb6** [comment]
0.2.3 no WS or UDP errors. Thanks!
