### ISSUE TITLE
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread in v3.1

### ISSUE THREAD

**Issue by norcoscia** [bpennypacker/WeatherFlow-Indigo-Plugin#33]
Hi, I started getting this error when I moved to version 3.1. Unfortunately that is also the time I changed some of the settings and added some triggers. I also added a new tempest device. Then I noticed the errors. I deleted the tempest device from indigo. Disabled all the new triggers, but the error below keeps happening. New to GitHub so hope I'm putting this in the right spot. Any help would be appreciated (I'm not a programmer).
Error list with debug on listed below - included photo of my configuration.
Norm

`WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 714, in runConcurrentThread
  File "plugin.py", line 610, in _process_message
  File "plugin.py", line 786, in process_obs_sky
IndexError: list index out of range

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds.

   WeatherFlow Smart Weather Debug {
    "firmware_revision": 43,
    "hub_sn": "HB-00013011",
    "obs": [
        [
            1612973234,
            4384,
            0.14,
            0.0,
            0.35,
            0.9,
            1.37,
            238,
            2.851,
            1,
            36,
            null,
            0,
            3
        ]
    ],
    "serial_number": "SK-00019648",
    "type": "obs_sky"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973235,
        1.31,
        189
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00015165",
    "ob": [
        1612973235,
        0.0,
        0
    ],
    "serial_number": "ST-00021308",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973241,
        1.43,
        197
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00015165",
    "ob": [
        1612973241,
        0.0,
        0
    ],
    "serial_number": "ST-00021308",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973244,
        1.43,
        194
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973247,
        0.92,
        99
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00015165",
    "ob": [
        1612973247,
        0.0,
        0
    ],
    "serial_number": "ST-00021308",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973250,
        1.29,
        194
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "firmware_revision": 22,
    "hub_sn": "HB-00013011",
    "obs": [
        [
            1612973251,
            1013.6,
            1.66,
            93,
            0,
            0,
            3.387,
            1
        ]
    ],
    "serial_number": "AR-00008472",
    "type": "obs_air"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973253,
        1.42,
        219
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00015165",
    "ob": [
        1612973253,
        0.0,
        0
    ],
    "serial_number": "ST-00021308",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973256,
        0.66,
        270
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "firmware_revision": 134,
    "hub_sn": "HB-00015165",
    "obs": [
        [
            1612973255,
            0.0,
            0.0,
            0.0,
            0,
            6,
            1019.1,
            0.62,
            96.14,
            3258,
            0.23,
            27,
            0.0,
            0,
            0,
            0,
            2.425,
            1
        ]
    ],
    "serial_number": "ST-00021308",
    "type": "obs_st"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973259,
        1.47,
        193
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00015165",
    "ob": [
        1612973259,
        0.0,
        0
    ],
    "serial_number": "ST-00021308",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973265,
        1.6,
        194
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00015165",
    "ob": [
        1612973265,
        0.0,
        0
    ],
    "serial_number": "ST-00021308",
    "type": "rapid_wind"
}
   WeatherFlow Smart Weather Debug {
    "hub_sn": "HB-00013011",
    "ob": [
        1612973268,
        1.45,
        214
    ],
    "serial_number": "SK-00019648",
    "type": "rapid_wind"
}`

![2021-02-10_08-16-09](https://user-images.githubusercontent.com/78313135/107538403-c9c04280-6b78-11eb-8242-952f12d869c6.png)

**Comment by bpennypacker** [comment]
You mention having a Tempest device, but the debug log you provided shows `"type": "obs_sky"` which is a notification from an older Sky device. Do you have one of those as well? The data sent from the old Sky device is in a slightly different format than the Tempest device, and the error you are showing seems to indicate Indigo thinks the message is for one type of WeatherFlow device but is being processed as if it's for the other type of device.

Probably the best way to confirm that this is the issue would be to completely delete all the WeatherFlow devices you have defined and then recreating them from scratch.

**Comment by norcoscia** [comment]
Hi, thanks for writing back. I have the sky and air, I just got a tempest - I was running both systems when the error started. I deleted the tempest device hoping it would stop the error. If I delete everything I will need to search through a lot of triggers, control pages and schedules trying to find (remember) all the places I have used any of the data. Is there any other way to fix it? I would rather take 2 aspirins before I do the lobotomy :-)

**Comment by norcoscia** [comment]
Oh, one other thing I noticed - when I had both units running I could not define (create) a rapid wind device for the newly added Tempest. The Tempest device did not show up to select but it did show up when I created the main Tempest device.....

**Comment by bpennypacker** [comment]
Instead of just deleting the devices and recreating them try defining new devices, moving the triggers, etc. to the new devices, then deleting the old ones.  It might also be worth disabling the old devices in Indigo first. Click on `Edit` for each device then uncheck the `Enable Indigo Communication` box at the bottom of the Edit window.

> Oh, one other thing I noticed - when I had both units running I could not define (create) a rapid wind device for the newly added Tempest. The Tempest device did not show up to select but it did show up when I created the main Tempest device.....

That's very odd. I'll have to see if I can set up both an Air & Tempest and see if I can recreate this behavior...

**Comment by norcoscia** [comment]
I disabled the 3 weather flow devices in indigo. Restarted the plug-in and no errors. Next I created a new rapid wind sky device and manually repointed all of my old rapid wind Indigo stuff to it. This took a bit of time but still no errors. 

Then I moved on to creating a new Sky device - as soon as I created it I started getting the errors in the log. I’m only guessing but it seems some changes in one of the versions (maybe 3.1) has created a problem with the legacy Sky/Air weather flow devices.

Not much more I can do since just creating the device caused the errors. Let me know if I can do anything to help or send any additional info.

**Comment by norcoscia** [comment]
To follow up, I decided to disable the Sky Rapid Wind device within Indigo to see if I could add a normal Sky device as a stand alone item (BTW, everything I’m doing is UDP). I reloaded the plug-in and created a Sky device - started getting the error. Next I deleated the Sky device and tried adding a tempest device. No issues or problems — so right now running w/o errors with Sky Rapid Wind and Tempest UDP devices.

**Comment by bpennypacker** [comment]
Thanks for all the additional information. This should be a big help when I'm able to test with both a Sky & Tempest device.

**Comment by bpennypacker** [comment]
I now have a Sky, Air, and Tempest and tried to recreate the issues you initially reported but haven't been able to. I did just fix a bug that prevented the creation of UDP rapid wind devices for the Tempest, so install 0.3.2 if you're running into that, and please let me know if you encounter any issues with it.

**Comment by norcoscia** [comment]
OK, thanks - in the middle of installing new fence around my house but will load up the new version and check out 3.2 as soon as possible... Stay safe :-)
