### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by jltnol** [bpennypacker/WeatherFlow-Indigo-Plugin#35]
this has been working fine but now I'm getting the same repeating error message:

WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 717, in runConcurrentThread
  File "plugin.py", line 645, in _process_message
  File "plugin.py", line 945, in process_obs_tempest
TypeError: list indices must be integers, not float

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by jrickmd** [comment]
I'm seeing the same thing.

**Comment by stackmk** [comment]
same thing

**Comment by bpennypacker** [comment]
I'm out of town for a few weeks. I'll take a look at this as soon as I can when I'm back.

**Comment by jltnol** [comment]
So as mysteriously as these error messages appeared, they have now disappeared.  Don't know what triggered them to start, much less to stop, but I'm not seeing these in my Indigo Log over the last 24 hours.

**Comment by bpennypacker** [comment]
Interesting. I wonder if they pushed out a firmware update with a bug in it and then fixed it. In any event I'll take a look when I can.

**Comment by jrickmd** [comment]
Yes, mine disappeared as well.

**Comment by stackmk** [comment]
I started getting the error messages on 12/14 and they continue today.  I am on firmware Hub 171, station 156.

**Comment by stackmk** [comment]
FYI - my errors stopped yesterday - errors 12/15 8:18am thur 12/17 16:57

**Comment by jltnol** [comment]
Aaaaaaaaand the are back:
`Dec 18, 2021 at 2:02:31 PM
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 717, in runConcurrentThread
  File "plugin.py", line 645, in _process_message
  File "plugin.py", line 945, in process_obs_tempest
TypeError: list indices must be integers, not float

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

Dec 18, 2021 at 2:03:09 PM
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 717, in runConcurrentThread
  File "plugin.py", line 645, in _process_message
  File "plugin.py", line 945, in process_obs_tempest
TypeError: list indices must be integers, not float

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds`

**Comment by jltnol** [comment]
And....it rained today.   Honestly don't remember, but I'm thinking the last time this happened was also a rainy day.   Can't confirm the connection, but would be good to see if others with the same errors had them on rain days.

**Comment by stackmk** [comment]
my errors started again today

**Comment by jltnol** [comment]
StackMK--did it rain where you are today ?

**Comment by stackmk** [comment]
I am eating crow here.  I chuckled when I saw jtnol's comment possibly connecting the log errors to rain then I checked into his theory.  I live in Colorado and rain has been so infrequent  that I thought originally that there is no way the errors could be connected (1" of rain in past 6 months).  I checked my Indigo logs and my Tempest history.  We got rain (0.03") on 12/15 between 8-30am.  My log errors started at 8:18am (I previously mistakenly said they started on 1214).  Today we received rain (0.07") between 3:00-3:30am).  My log errors started at 3:14am.   So jtnol I bow to you.  It does seems connected to rain.  WTF

**Comment by aldera123** [comment]
Getting the same error:

   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 717, in runConcurrentThread
  File "plugin.py", line 645, in _process_message
  File "plugin.py", line 945, in process_obs_tempest
TypeError: list indices must be integers, not float

**Comment by jrickmd** [comment]
Same errors are back for me. It started immediately after the Tempest turned on the "it's raining" sensor.

`Jan 2, 2022 at 3:22:27 AM
   Trigger                         WeatherFlow Rain Activate
   Action Group                    Turn All Sprinklers OFF
   Trigger                         Rain Gauge Last Wet Updated
   Script                          rain gauge wet at Sunday, January 02, 2022 03:22
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 717, in runConcurrentThread
  File "plugin.py", line 645, in _process_message
  File "plugin.py", line 945, in process_obs_tempest
TypeError: list indices must be integers, not float

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
`

With debug showing

`   WeatherFlow Smart Weather Debug {
    "device_id": 65669,
    "firmware_revision": 165,
    "hub_sn": "HB-00023026",
    "obs": [
        [
            1641131301,
            0.08,
            1.08,
            1.96,
            333,
            3,
            1019.8,
            -0.2,
            68,
            1802,
            1.46,
            15,
            0.0,
            0,
            0,
            0,
            2.62,
            1,
            0.057828,
            0.0,
            0.001216,
            0
        ]
    ],
    "serial_number": "ST-00054225",
    "source": "mqtt",
    "summary": {
        "air_density": 1.30155,
        "delta_t": 1.8,
        "dew_point": -5.4,
        "feels_like": -0.2,
        "heat_index": -0.2,
        "precip_accum_local_yesterday": 0.0,
        "precip_accum_local_yesterday_final": 0.0,
        "precip_analysis_type_yesterday": 1,
        "precip_minutes_local_day": 6,
        "precip_minutes_local_yesterday": 0,
        "precip_total_1h": 0.0,
        "pressure_trend": "rising",
        "pulse_adj_ob_temp": -0.2,
        "pulse_adj_ob_time": 1641131241,
        "pulse_adj_ob_wind_avg": 0.6,
        "raining_minutes": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "strike_count_1h": 0,
        "strike_count_3h": 0,
        "strike_last_dist": 18,
        "strike_last_epoch": 1639858313,
        "wet_bulb_temperature": -2.0,
        "wind_chill": -0.2
    },
    "type": "obs_st"
}
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:
`

Rick

**Comment by bpennypacker** [comment]
It appears that the WeatherFlow team did indeed add a new field to the Tempest observations, but rather than add the new field to the end of the data structure they made it second to last. Their [documentation](https://weatherflow.github.io/Tempest/api/ws.html) for Tempest observations (obs_st) shows 21 values when it used to be 20. "Precipitation Analysis Type" is now at index 21 where it used to be 20, and 20 is a new "Local Daily Rain Accumulation Final (Rain Check)" value. This should be easy enough to fix...

**Comment by bpennypacker** [comment]
I just published [v0.3.3](https://github.com/bpennypacker/WeatherFlow-Indigo-Plugin/releases/tag/v0.3.3). Please give it a try and let me know if it fixes this.

**Comment by jltnol** [comment]
Thanks for the update.   Will keep an eye out to see what happens.

**Comment by jltnol** [comment]
FWIW, and I understand there may be some disagreement on what triggers the error messages, I've had a few instances of rain today, but no error messages. Thanks

**Comment by lloydaviation** [comment]
OK, I just upgraded to 0.3.3 and I am getting the exact same set of error messages, i.e.:

Jan 22, 2022 at 16:56:35
   WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 717, in runConcurrentThread
  File "plugin.py", line 613, in _process_message
  File "plugin.py", line 789, in process_obs_sky
IndexError: list index out of range

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

So ... apparently not quite fixed.
